using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Windows.Forms;

namespace Takdir_Tesekkür_Hesapla
{
    public partial class _9_Sinif_Meslek : Form
    {
        public _9_Sinif_Meslek()
        {
            InitializeComponent();
        }

        private void visibleFalse()
        {
            lblCizgi1.Visible = false;
            lblCizgi2.Visible = false;
            lblCizgi3.Visible = false;
            lblCizgi4.Visible = false;
            lblCizgi5.Visible = false;
            lblCizgi6.Visible = false;
            lblCizgi7.Visible = false;
            lblCizgi8.Visible = false;
            lblCizgi9.Visible = false;
            lblCizgi10.Visible = false;
            lblCizgi11.Visible = false;
            lblCizgi12.Visible = false;
            lblCizgi13.Visible = false;
            lblCizgi14.Visible = false;
            lblCizgi15.Visible = false;
            lblCizgi16.Visible = false;
            lblCizgi17.Visible = false;
            lblCizgi18.Visible = false;
            lblCizgi19.Visible = false;
            lblCizgi20.Visible = false;
            lblCizgi21.Visible = false;
            lblCizgi22.Visible = false;
            lblCizgi23.Visible = false;
            lblCizgi24.Visible = false;
            lblCizgi25.Visible = false;
            lblCizgi26.Visible = false;
            lblCizgi27.Visible = false;
            lblCizgi28.Visible = false;
            lblCizgi29.Visible = false;
            lblCizgi30.Visible = false;
            cmbDers1.Visible = false;
            cmbDers2.Visible = false;
            cmbDers3.Visible = false;
            cmbDers4.Visible = false;
            cmbDers5.Visible = false;
            cmbDers6.Visible = false;
            cmbDers7.Visible = false;
            cmbDers8.Visible = false;
            cmbDers9.Visible = false;
            cmbDers10.Visible = false;
            cmbDers11.Visible = false;
            cmbDers12.Visible = false;
            cmbDers13.Visible = false;
            cmbDers14.Visible = false;
            cmbDers15.Visible = false;
            cmbSaat1.Visible = false;
            cmbSaat2.Visible = false;
            cmbSaat3.Visible = false;
            cmbSaat4.Visible = false;
            cmbSaat5.Visible = false;
            cmbSaat6.Visible = false;
            cmbSaat7.Visible = false;
            cmbSaat8.Visible = false;
            cmbSaat9.Visible = false;
            cmbSaat10.Visible = false;
            cmbSaat11.Visible = false;
            cmbSaat12.Visible = false;
            cmbSaat13.Visible = false;
            cmbSaat14.Visible = false;
            cmbSaat15.Visible = false;
            txtPuan1.Visible = false;
            txtPuan2.Visible = false;
            txtPuan3.Visible = false;
            txtPuan4.Visible = false;
            txtPuan5.Visible = false;
            txtPuan6.Visible = false;
            txtPuan7.Visible = false;
            txtPuan8.Visible = false;
            txtPuan9.Visible = false;
            txtPuan10.Visible = false;
            txtPuan11.Visible = false;
            txtPuan12.Visible = false;
            txtPuan13.Visible = false;
            txtPuan14.Visible = false;
            txtPuan15.Visible = false;
        }
        private void cmbDersSaatler_SelectedIndexChanged(object sender, EventArgs e)
        {
            if (cmbDersSaatler.SelectedItem.ToString()=="1")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString()=="2")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString()=="3")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString()=="4")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "5")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
                txtPuan5.Visible = true;
                cmbSaat5.Visible = true;
                cmbDers5.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi5.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "6")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
                txtPuan5.Visible = true;
                cmbSaat5.Visible = true;
                cmbDers5.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi5.Visible = true;
                txtPuan6.Visible = true;
                cmbSaat6.Visible = true;
                cmbDers6.Visible = true;
                lblCizgi21.Visible = true;
                lblCizgi6.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "7")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
                txtPuan5.Visible = true;
                cmbSaat5.Visible = true;
                cmbDers5.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi5.Visible = true;
                txtPuan6.Visible = true;
                cmbSaat6.Visible = true;
                cmbDers6.Visible = true;
                lblCizgi21.Visible = true;
                lblCizgi6.Visible = true;
                txtPuan7.Visible = true;
                cmbSaat7.Visible = true;
                cmbDers7.Visible = true;
                lblCizgi22.Visible = true;
                lblCizgi7.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "8")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
                txtPuan5.Visible = true;
                cmbSaat5.Visible = true;
                cmbDers5.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi5.Visible = true;
                txtPuan6.Visible = true;
                cmbSaat6.Visible = true;
                cmbDers6.Visible = true;
                lblCizgi21.Visible = true;
                lblCizgi6.Visible = true;
                txtPuan7.Visible = true;
                cmbSaat7.Visible = true;
                cmbDers7.Visible = true;
                lblCizgi22.Visible = true;
                lblCizgi7.Visible = true;
                txtPuan8.Visible = true;
                cmbSaat8.Visible = true;
                cmbDers8.Visible = true;
                lblCizgi23.Visible = true;
                lblCizgi8.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "9")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
                txtPuan5.Visible = true;
                cmbSaat5.Visible = true;
                cmbDers5.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi5.Visible = true;
                txtPuan6.Visible = true;
                cmbSaat6.Visible = true;
                cmbDers6.Visible = true;
                lblCizgi21.Visible = true;
                lblCizgi6.Visible = true;
                txtPuan7.Visible = true;
                cmbSaat7.Visible = true;
                cmbDers7.Visible = true;
                lblCizgi22.Visible = true;
                lblCizgi7.Visible = true;
                txtPuan8.Visible = true;
                cmbSaat8.Visible = true;
                cmbDers8.Visible = true;
                lblCizgi23.Visible = true;
                lblCizgi8.Visible = true;
                txtPuan9.Visible = true;
                cmbSaat9.Visible = true;
                cmbDers9.Visible = true;
                lblCizgi24.Visible = true;
                lblCizgi9.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "10")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
                txtPuan5.Visible = true;
                cmbSaat5.Visible = true;
                cmbDers5.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi5.Visible = true;
                txtPuan6.Visible = true;
                cmbSaat6.Visible = true;
                cmbDers6.Visible = true;
                lblCizgi21.Visible = true;
                lblCizgi6.Visible = true;
                txtPuan7.Visible = true;
                cmbSaat7.Visible = true;
                cmbDers7.Visible = true;
                lblCizgi22.Visible = true;
                lblCizgi7.Visible = true;
                txtPuan8.Visible = true;
                cmbSaat8.Visible = true;
                cmbDers8.Visible = true;
                lblCizgi23.Visible = true;
                lblCizgi8.Visible = true;
                txtPuan9.Visible = true;
                cmbSaat9.Visible = true;
                cmbDers9.Visible = true;
                lblCizgi24.Visible = true;
                lblCizgi9.Visible = true;
                txtPuan10.Visible = true;
                cmbSaat10.Visible = true;
                cmbDers10.Visible = true;
                lblCizgi25.Visible = true;
                lblCizgi10.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "11")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
                txtPuan5.Visible = true;
                cmbSaat5.Visible = true;
                cmbDers5.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi5.Visible = true;
                txtPuan6.Visible = true;
                cmbSaat6.Visible = true;
                cmbDers6.Visible = true;
                lblCizgi21.Visible = true;
                lblCizgi6.Visible = true;
                txtPuan7.Visible = true;
                cmbSaat7.Visible = true;
                cmbDers7.Visible = true;
                lblCizgi22.Visible = true;
                lblCizgi7.Visible = true;
                txtPuan8.Visible = true;
                cmbSaat8.Visible = true;
                cmbDers8.Visible = true;
                lblCizgi23.Visible = true;
                lblCizgi8.Visible = true;
                txtPuan9.Visible = true;
                cmbSaat9.Visible = true;
                cmbDers9.Visible = true;
                lblCizgi24.Visible = true;
                lblCizgi9.Visible = true;
                txtPuan10.Visible = true;
                cmbSaat10.Visible = true;
                cmbDers10.Visible = true;
                lblCizgi25.Visible = true;
                lblCizgi10.Visible = true;
                txtPuan11.Visible = true;
                cmbSaat11.Visible = true;
                cmbDers11.Visible = true;
                lblCizgi26.Visible = true;
                lblCizgi11.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "12")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
                txtPuan5.Visible = true;
                cmbSaat5.Visible = true;
                cmbDers5.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi5.Visible = true;
                txtPuan6.Visible = true;
                cmbSaat6.Visible = true;
                cmbDers6.Visible = true;
                lblCizgi21.Visible = true;
                lblCizgi6.Visible = true;
                txtPuan7.Visible = true;
                cmbSaat7.Visible = true;
                cmbDers7.Visible = true;
                lblCizgi22.Visible = true;
                lblCizgi7.Visible = true;
                txtPuan8.Visible = true;
                cmbSaat8.Visible = true;
                cmbDers8.Visible = true;
                lblCizgi23.Visible = true;
                lblCizgi8.Visible = true;
                txtPuan9.Visible = true;
                cmbSaat9.Visible = true;
                cmbDers9.Visible = true;
                lblCizgi24.Visible = true;
                lblCizgi9.Visible = true;
                txtPuan10.Visible = true;
                cmbSaat10.Visible = true;
                cmbDers10.Visible = true;
                lblCizgi25.Visible = true;
                lblCizgi10.Visible = true;
                txtPuan11.Visible = true;
                cmbSaat11.Visible = true;
                cmbDers11.Visible = true;
                lblCizgi26.Visible = true;
                lblCizgi11.Visible = true;
                txtPuan12.Visible = true;
                cmbSaat12.Visible = true;
                cmbDers12.Visible = true;
                lblCizgi27.Visible = true;
                lblCizgi12.Visible = true;
                
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "13")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
                txtPuan5.Visible = true;
                cmbSaat5.Visible = true;
                cmbDers5.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi5.Visible = true;
                txtPuan6.Visible = true;
                cmbSaat6.Visible = true;
                cmbDers6.Visible = true;
                lblCizgi21.Visible = true;
                lblCizgi6.Visible = true;
                txtPuan7.Visible = true;
                cmbSaat7.Visible = true;
                cmbDers7.Visible = true;
                lblCizgi22.Visible = true;
                lblCizgi7.Visible = true;
                txtPuan8.Visible = true;
                cmbSaat8.Visible = true;
                cmbDers8.Visible = true;
                lblCizgi23.Visible = true;
                lblCizgi8.Visible = true;
                txtPuan9.Visible = true;
                cmbSaat9.Visible = true;
                cmbDers9.Visible = true;
                lblCizgi24.Visible = true;
                lblCizgi9.Visible = true;
                txtPuan10.Visible = true;
                cmbSaat10.Visible = true;
                cmbDers10.Visible = true;
                lblCizgi25.Visible = true;
                lblCizgi10.Visible = true;
                txtPuan11.Visible = true;
                cmbSaat11.Visible = true;
                cmbDers11.Visible = true;
                lblCizgi26.Visible = true;
                lblCizgi11.Visible = true;
                txtPuan12.Visible = true;
                cmbSaat12.Visible = true;
                cmbDers12.Visible = true;
                lblCizgi27.Visible = true;
                lblCizgi12.Visible = true;
                txtPuan13.Visible = true;
                cmbSaat13.Visible = true;
                cmbDers13.Visible = true;
                lblCizgi28.Visible = true;
                lblCizgi13.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "14")
            {
                visibleFalse();
                lblDersler.Visible = true;
                lblPuan.Visible = true;
                lblSaat.Visible = true;
                cmbDers1.Visible = true;
                txtPuan1.Visible = true;
                lblCizgi1.Visible = true;
                lblCizgi16.Visible = true;
                cmbSaat1.Visible = true;
                txtPuan2.Visible = true;
                cmbSaat2.Visible = true;
                cmbDers2.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi2.Visible = true;
                txtPuan3.Visible = true;
                cmbSaat3.Visible = true;
                cmbDers3.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi3.Visible = true;
                txtPuan4.Visible = true;
                cmbSaat4.Visible = true;
                cmbDers4.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi4.Visible = true;
                txtPuan5.Visible = true;
                cmbSaat5.Visible = true;
                cmbDers5.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi5.Visible = true;
                txtPuan6.Visible = true;
                cmbSaat6.Visible = true;
                cmbDers6.Visible = true;
                lblCizgi21.Visible = true;
                lblCizgi6.Visible = true;
                txtPuan7.Visible = true;
                cmbSaat7.Visible = true;
                cmbDers7.Visible = true;
                lblCizgi22.Visible = true;
                lblCizgi7.Visible = true;
                txtPuan8.Visible = true;
                cmbSaat8.Visible = true;
                cmbDers8.Visible = true;
                lblCizgi23.Visible = true;
                lblCizgi8.Visible = true;
                txtPuan9.Visible = true;
                cmbSaat9.Visible = true;
                cmbDers9.Visible = true;
                lblCizgi24.Visible = true;
                lblCizgi9.Visible = true;
                txtPuan10.Visible = true;
                cmbSaat10.Visible = true;
                cmbDers10.Visible = true;
                lblCizgi25.Visible = true;
                lblCizgi10.Visible = true;
                txtPuan11.Visible = true;
                cmbSaat11.Visible = true;
                cmbDers11.Visible = true;
                lblCizgi26.Visible = true;
                lblCizgi11.Visible = true;
                txtPuan12.Visible = true;
                cmbSaat12.Visible = true;
                cmbDers12.Visible = true;
                lblCizgi27.Visible = true;
                lblCizgi12.Visible = true;
                txtPuan13.Visible = true;
                cmbSaat13.Visible = true;
                cmbDers13.Visible = true;
                lblCizgi28.Visible = true;
                lblCizgi13.Visible = true;
                txtPuan14.Visible = true;
                cmbSaat14.Visible = true;
                cmbDers14.Visible = true;
                lblCizgi29.Visible = true;
                lblCizgi14.Visible = true;
            }
            else if (cmbDersSaatler.SelectedItem.ToString() == "15")
            {
                lblCizgi1.Visible = true;
                lblCizgi2.Visible = true;
                lblCizgi3.Visible = true;
                lblCizgi4.Visible = true;
                lblCizgi5.Visible = true;
                lblCizgi6.Visible = true;
                lblCizgi7.Visible = true;
                lblCizgi8.Visible = true;
                lblCizgi9.Visible = true;
                lblCizgi10.Visible = true;
                lblCizgi11.Visible = true;
                lblCizgi12.Visible = true;
                lblCizgi13.Visible = true;
                lblCizgi14.Visible = true;
                lblCizgi15.Visible = true;
                lblCizgi16.Visible = true;
                lblCizgi17.Visible = true;
                lblCizgi18.Visible = true;
                lblCizgi19.Visible = true;
                lblCizgi20.Visible = true;
                lblCizgi21.Visible = true;
                lblCizgi22.Visible = true;
                lblCizgi23.Visible = true;
                lblCizgi24.Visible = true;
                lblCizgi25.Visible = true;
                lblCizgi26.Visible = true;
                lblCizgi27.Visible = true;
                lblCizgi28.Visible = true;
                lblCizgi29.Visible = true;
                lblCizgi30.Visible = true;
                cmbDers1.Visible = true;
                cmbDers2.Visible = true;
                cmbDers3.Visible = true;
                cmbDers4.Visible = true;
                cmbDers5.Visible = true;
                cmbDers6.Visible = true;
                cmbDers7.Visible = true;
                cmbDers8.Visible = true;
                cmbDers9.Visible = true;
                cmbDers10.Visible = true;
                cmbDers11.Visible = true;
                cmbDers12.Visible = true;
                cmbDers13.Visible = true;
                cmbDers14.Visible = true;
                cmbDers15.Visible = true;
                cmbSaat1.Visible = true;
                cmbSaat2.Visible = true;
                cmbSaat3.Visible = true;
                cmbSaat4.Visible = true;
                cmbSaat5.Visible = true;
                cmbSaat6.Visible = true;
                cmbSaat7.Visible = true;
                cmbSaat8.Visible = true;
                cmbSaat9.Visible = true;
                cmbSaat10.Visible = true;
                cmbSaat11.Visible = true;
                cmbSaat12.Visible = true;
                cmbSaat13.Visible = true;
                cmbSaat14.Visible = true;
                cmbSaat15.Visible = true;
                txtPuan1.Visible = true;
                txtPuan2.Visible = true;
                txtPuan3.Visible = true;
                txtPuan4.Visible = true;
                txtPuan5.Visible = true;
                txtPuan6.Visible = true;
                txtPuan7.Visible = true;
                txtPuan8.Visible = true;
                txtPuan9.Visible = true;
                txtPuan10.Visible = true;
                txtPuan11.Visible = true;
                txtPuan12.Visible = true;
                txtPuan13.Visible = true;
                txtPuan14.Visible = true;
                txtPuan15.Visible = true;
            }
            
        }
    }
}
